name: ğŸš€ Deploy to Render

on:
  push:
    branches:
      - main  # ou master selon ta branche principale

jobs:
  deploy:
    name: ğŸ”„ Trigger Render Deploy Hooks
    runs-on: ubuntu-latest

    steps:

      - name: ğŸ” Trigger backend deployment
        run: |
          curl -X POST https://api.render.com/deploy/srv-d27sprm3jp1c73fnb9dg?key=hKEOTrBrV2M
